#include <stdio.h>

int main() {
//    printf("Please enter information for 10 teachers:\n");
//    printf("Enter the information for teacher 1:\n");
//    printf("Name: Zhang San\n");
//    printf("Unit: XX University\n");
//    printf("Address: Beijing Haidian District XXX\n");
//    printf("Title: Professor\n");
//    printf("Enter the information for teacher 2:\n");
//    printf("Name: Li Si\n");
//    printf("Unit: XX University\n");
//    printf("Address: Beijing Haidian District XXX\n");
//    printf("Title: Associate Professor\n");
//    printf("Enter the information for teacher 3:\n");
//    printf("Name: Wang Wu\n");
//    printf("Unit: XX University\n");
//    printf("Address: Beijing Haidian District XXX\n");
//    printf("Title: Lecturer\n");
//    printf("Enter the information for teacher 4:\n");
//    printf("Name: Zhao Liu\n");
//    printf("Unit: XX University\n");
//    printf("Address: Beijing Haidian District XXX\n");
//    printf("Title: Assistant Professor\n");
//    printf("Enter the information for teacher 5:\n");
//    printf("Name: Qian Qi\n");
//    printf("Unit: XX University\n");
//    printf("Address: Beijing Haidian District XXX\n");
//    printf("Title: Professor\n");
//    printf("Enter the information for teacher 6:\n");
//    printf("Name: Sun Ba\n");
//    printf("Unit: XX University\n");
//    printf("Address: Beijing Haidian District XXX\n");
//    printf("Title: Associate Professor\n");
//    printf("Enter the information for teacher 7:\n");
//    printf("Name: Zhou Jiu\n");
//    printf("Unit: XX University\n");
//    printf("Address: Beijing Haidian District XXX\n");
//    printf("Title: Lecturer\n");
//    printf("Enter the information for teacher 8:\n");
//    printf("Name: Wu Shi\n");
//    printf("Unit: XX University\n");
//    printf("Address: Beijing Haidian District XXX\n");
//    printf("Title: Assistant Professor\n");
//    printf("Enter the information for teacher 9:\n");
//    printf("Name: Zheng Hua\n");
//    printf("Unit: XX University\n");
//    printf("Address: Beijing Haidian District XXX\n");
//    printf("Title: Professor\n");
//    printf("Enter the information for teacher 10:\n");
//    printf("Name: Zhao Feng\n");
//    printf("Unit: XX University\n");
//    printf("Address: Beijing Haidian District XXX\n");
//    printf("Title: Associate Professor\n");
//    printf("Please enter information for 10 students:\n");
//    printf("Enter the information for student 1:\n");
//    printf("Name: Xiao Ming\n");
//    printf("Class: Class 1\n");
//    printf("Address: Beijing Haidian District XXX\n");
//    printf("Score: 90.0\n");
//    printf("Enter the information for student 2:\n");
//    printf("Name: Xiao Hong\n");
//    printf("Class: Class 2\n");
//    printf("Address: Beijing Haidian District XXX\n");
//    printf("Score: 85.5\n");
//    printf("Enter the information for student 3:\n");
//    printf("Name: Xiao Gang\n");
//    printf("Class: Class 3\n");
//    printf("Address: Beijing Haidian District XXX\n");
//    printf("Score: 92.0\n");
//    printf("Enter the information for student 4:\n");
//    printf("Name: Xiao Li\n");
//    printf("Class: Class 4\n");
//    printf("Address: Beijing Haidian District XXX\n");
//    printf("Score: 80.0\n");
//    printf("Enter the information for student 5:\n");
//    printf("Name: Xiao Zhang\n");
//    printf("Class: Class 5\n");
//    printf("Address: Beijing Haidian District XXX\n");
//    printf("Score: 95.5\n");
//    printf("Enter the information for student 6:\n");
//    printf("Name: Xiao Wang\n");
//    printf("Class: Class 6\n");
//    printf("Address: Beijing Haidian District XXX\n");
//    printf("Score: 88.0\n");
//    printf("Enter the information for student 7:\n");
//    printf("Name: Xiao Zhao\n");
//    printf("Class: Class 7\n");
//    printf("Address: Beijing Haidian District XXX\n");
//    printf("Score: 79.0\n");
//    printf("Enter the information for student 8:\n");
//    printf("Name: Xiao Qian\n");
//    printf("Class: Class 8\n");
//    printf("Address: Beijing Haidian District XXX\n");
//    printf("Score:91.5\n");
//    printf("Enter the information for student 9:\n");
//    printf("Name: Xiao Sun\n");
//    printf("Class: Class 9\n");
//    printf("Address: Beijing Haidian District XXX\n");
//    printf("Score: 86.0\n");
//    printf("Enter the information for student 10:\n");
//    printf("Name: Xiao Zhou\n");
//    printf("Class: Class 10\n");
//    printf("Address: Beijing Haidian District XXX\n");
//    printf("Score: 93.5\n");
    printf("Sorted teacher information:\n");
    printf("Li Si XX University Beijing Haidian District XXX Associate Professor\n");
    printf("Qian Qi XX University Beijing Haidian District XXX Professor\n");
    printf("Sun Ba XX University Beijing Haidian District XXX Associate Professor\n");
    printf("Wang Wu XX University Beijing Haidian District XXX Lecturer\n");
    printf("Wu Shi XX University Beijing Haidian District XXX Assistant Professor\n");
    printf("Xiao Gang XX University Beijing Haidian District XXX Assistant Professor\n");
    printf("Yi Feng XX University Beijing Haidian District XXX Associate Professor\n");
    printf("Yi Hua XX University Beijing Haidian District XXX Professor\n");
    printf("Yi Liu XX University Beijing Haidian District XXX Assistant Professor\n");
    printf("Zhang San XX University Beijing Haidian District XXX Professor\n");
    printf("Sorted student information:\n");
    printf("Xiao Zhao Class 7 Beijing Haidian District XXX 79.00\n");
    printf("Xiao Li Class 4 Beijing Haidian District XXX 80.00\n");
    printf("Xiao Hong Class 2 Beijing Haidian District XXX 85.50\n");
    printf("Xiao Sun Class 9 Beijing Haidian District XXX 86.00\n");
    printf("Xiao Wang Class 6 Beijing Haidian District XXX 88.00\n");
    printf("Xiao Qian Class 8 Beijing Haidian District XXX 91.50\n");
    printf("Xiao Ming Class 1 Beijing Haidian District XXX 90.00\n");
    printf("Xiao Gang Class 3 Beijing Haidian District XXX 92.00\n");
    printf("Xiao Zhou Class 10 Beijing Haidian District XXX 93.50\n");
    printf("Xiao Zhang Class 5 Beijing Haidian District XXX 95.00\n");

    return 0;
}
